import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  scrollView: {flex: 1, backgroundColor: 'white'},
  container: {
    flex: 1,
    paddingBottom: 40,
  },
  linearGradientContainer: {
    height: 250,
    borderRadius: 15,
    marginHorizontal: 10,
    zIndex: -1,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
  innerContainer: {
    marginTop: 30,
  },
  iconContainer: {flexDirection: 'row', marginLeft: 20, alignItems: 'center'},
  goBackText: {color: 'white', fontWeight: '300', fontSize: 14},
  welcomeText: {
    textAlign: 'center',
    marginTop: 20,
    color: 'white',
    fontWeight: 'bold',
    fontSize: 24,
    marginLeft: 10,
    letterSpacing: 1,
  },
  dropShadowStyle: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  shadowContainer: {
    marginTop: 40,
    marginHorizontal: 40,
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.5)',
    padding: 20,
  },
  blurView: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    borderRadius: 15,
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  dividerStyle: {height: 1, width: 60},
  orText: {marginHorizontal: 10, textAlign: 'center', fontSize: 12},
  registerText: {
    textAlign: 'center',
    color: 'black',
    fontWeight: 'bold',
    fontSize: 14,
    marginLeft: 10,
  },
  socialContainer: {
    width: '80%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignSelf: 'center',
  },
  imageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    borderColor: 'gray',
    borderWidth: 1,
    padding: 10,
    marginTop: 20,
  },
  imageStyle: {
    resizeMode: 'contain',
    width: 20,
    height: 20,
  },
  labelStyle: {
    marginTop: 20,
    color: 'black',
    fontWeight: 'bold',
    fontSize: 12,
  },
  inputStyle: {
    borderRadius: 8,
    borderColor: '#e0e1e3',
    borderWidth: 1,
    height: 40,
    paddingHorizontal: 10,
    marginTop: 10,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderColor: 'red',
  },
  termsTextStyle: {
    color: '#747881',
    fontWeight: '500',
    fontSize: 12,
    marginLeft: 10,
  },
  signUpButton: {
    opacity: 0.4,
    height: 45,
    borderRadius: 10,
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  signUpTextStyle: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
  },
  signInButton: {
    height: 45,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#c44caa',
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  signInTextStyle: {
    color: '#c44caa',
    fontWeight: '800',
    fontSize: 14,
  },
});
